# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1016, 773)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.btn_search = QtWidgets.QPushButton(self.centralwidget)
        self.btn_search.setObjectName("btn_search")
        self.horizontalLayout.addWidget(self.btn_search)
        self.btn_pause = QtWidgets.QPushButton(self.centralwidget)
        self.btn_pause.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_pause.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_pause.setFlat(True)
        self.btn_pause.setObjectName("btn_pause")
        self.horizontalLayout.addWidget(self.btn_pause)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(300, 0))
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tableWidget_wangyi = QtWidgets.QTableWidget(self.tab_6)
        self.tableWidget_wangyi.setObjectName("tableWidget_wangyi")
        self.tableWidget_wangyi.setColumnCount(4)
        self.tableWidget_wangyi.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_wangyi.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_wangyi.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_wangyi.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_wangyi.setHorizontalHeaderItem(3, item)
        self.gridLayout_2.addWidget(self.tableWidget_wangyi, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_7)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget_qq = QtWidgets.QTableWidget(self.tab_7)
        self.tableWidget_qq.setObjectName("tableWidget_qq")
        self.tableWidget_qq.setColumnCount(4)
        self.tableWidget_qq.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_qq.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_qq.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_qq.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_qq.setHorizontalHeaderItem(3, item)
        self.gridLayout.addWidget(self.tableWidget_qq, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_7, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tableWidget_kugou = QtWidgets.QTableWidget(self.tab)
        self.tableWidget_kugou.setObjectName("tableWidget_kugou")
        self.tableWidget_kugou.setColumnCount(4)
        self.tableWidget_kugou.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_kugou.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_kugou.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_kugou.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_kugou.setHorizontalHeaderItem(3, item)
        self.gridLayout_3.addWidget(self.tableWidget_kugou, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tableWidget_kuwo = QtWidgets.QTableWidget(self.tab_4)
        self.tableWidget_kuwo.setObjectName("tableWidget_kuwo")
        self.tableWidget_kuwo.setColumnCount(4)
        self.tableWidget_kuwo.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_kuwo.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_kuwo.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_kuwo.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_kuwo.setHorizontalHeaderItem(3, item)
        self.gridLayout_4.addWidget(self.tableWidget_kuwo, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tableWidget_migu = QtWidgets.QTableWidget(self.tab_5)
        self.tableWidget_migu.setObjectName("tableWidget_migu")
        self.tableWidget_migu.setColumnCount(4)
        self.tableWidget_migu.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_migu.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_migu.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_migu.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_migu.setHorizontalHeaderItem(3, item)
        self.gridLayout_5.addWidget(self.tableWidget_migu, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.tableWidget_xiami = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_xiami.setObjectName("tableWidget_xiami")
        self.tableWidget_xiami.setColumnCount(4)
        self.tableWidget_xiami.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_xiami.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_xiami.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_xiami.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_xiami.setHorizontalHeaderItem(3, item)
        self.gridLayout_6.addWidget(self.tableWidget_xiami, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.tableWidget_qianqian = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget_qianqian.setObjectName("tableWidget_qianqian")
        self.tableWidget_qianqian.setColumnCount(4)
        self.tableWidget_qianqian.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_qianqian.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_qianqian.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_qianqian.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_qianqian.setHorizontalHeaderItem(3, item)
        self.gridLayout_7.addWidget(self.tableWidget_qianqian, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "音乐下载工具"))
        self.btn_search.setText(_translate("MainWindow", "搜索"))
        self.btn_pause.setText(_translate("MainWindow", "口"))
        self.tabWidget.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.tabWidget.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        item = self.tableWidget_wangyi.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "歌名"))
        item = self.tableWidget_wangyi.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "歌手"))
        item = self.tableWidget_wangyi.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "时长"))
        item = self.tableWidget_wangyi.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "下载"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "网易云"))
        item = self.tableWidget_qq.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "歌名"))
        item = self.tableWidget_qq.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "歌手"))
        item = self.tableWidget_qq.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "时长"))
        item = self.tableWidget_qq.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "下载"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "QQ"))
        item = self.tableWidget_kugou.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "歌名"))
        item = self.tableWidget_kugou.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "歌手"))
        item = self.tableWidget_kugou.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "时长"))
        item = self.tableWidget_kugou.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "下载"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "酷狗"))
        item = self.tableWidget_kuwo.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "歌名"))
        item = self.tableWidget_kuwo.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "歌手"))
        item = self.tableWidget_kuwo.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "时长"))
        item = self.tableWidget_kuwo.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "下载"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "酷我"))
        item = self.tableWidget_migu.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "歌名"))
        item = self.tableWidget_migu.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "歌手"))
        item = self.tableWidget_migu.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "时长"))
        item = self.tableWidget_migu.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "下载"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "咪咕"))
        item = self.tableWidget_xiami.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "歌名"))
        item = self.tableWidget_xiami.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "歌手"))
        item = self.tableWidget_xiami.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "时长"))
        item = self.tableWidget_xiami.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "下载"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "虾米"))
        item = self.tableWidget_qianqian.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "歌名"))
        item = self.tableWidget_qianqian.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "歌手"))
        item = self.tableWidget_qianqian.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "时长"))
        item = self.tableWidget_qianqian.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "下载"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "千千静听"))
